### ISSUE TITLE
registry URI predictable ?

### ISSUE THREAD

**Issue by fabcotech** [rchain/rchain#3305]
Right now the unforgeable names (for example `new x, y in { ... }`) are predictable with explore-deploy API.

Is there a possibility that the registry URIs could also be predictable ?

**Comment by zsluedem** [comment]
It depends on which kind of insert you are using for .

`InsertSigned` is used by your public key to generate the URIs which you can predict directly from your public key. Because of that, however, one key can only insert one thing in registry.(related issue https://github.com/rchain/rchain/issues/3296)

`InsertArbitrary` would generate an unforgeable name each time to generate the URIs -> [related code](https://github.com/rchain/rchain/blob/30e5407d210e87f7804018544868fbe01ac38f19/casper/src/main/resources/Registry.rho#L369), which means every time you use `InsertArbitrary` would get different URIs. The unforgeable name which is generated not on the root scope is a little bit different from the way how explore-deploy API work because the random seed used for generating unforgeable name would change on [dispatcher](https://github.com/rchain/rchain/blob/30e5407d210e87f7804018544868fbe01ac38f19/rholang/src/main/scala/coop/rchain/rholang/interpreter/dispatch.scala#L35-L38).
Anyway, I never tried to predict an unforgeable name not in root scope before. But I believe this is very difficult and it also depends on how you wrote the contract.

**Comment by zsluedem** [comment]
Feel free to open if you have any more questions .

**Comment by tgrospic** [comment]
@fabcotech We are removing predictable unforgeable names, for security reasons and because they are not necessary for changed Registry insertSigned method.

Registry `insertSigned` method generates URI from DeployerId which means it's predictable and stays the same after update. 
- #3669
