### ISSUE TITLE
Unforgeable names in a bundle are not converted to JSON in WebAPI

### ISSUE THREAD

**Issue by jimscarver** [rchain/rchain#3317]
### What did you expect to see?
unforgeable names stored in maps and lists
### What did you see instead?
nothing, the terms are ommitted.
### Steps to reproduce the bug

try of same test done in deploy of issue.rho
```scala
match ["inbox", "", Set(), `rho:id:wqcedk93naqxunhmhjdmk9qgg88o9d1aak8kpy4mqe618ow6bgxpg5`] {
  [lockerTag, name, proposals, issueURI] => {
    
    new lookupCh, bCh, lookup(`rho:registry:lookup`),
    return(`rho:rchain:deployId`),
    trace(`rho:rchain:deployId`) in {
      lookup!(issueURI, *lookupCh) |
      for(Issue <- lookupCh) {
        new bCh, v1Ch, v2Ch, v3Ch, v4Ch in {
          trace!("creating Issue") |
          Issue!(Set("Lincoln", "Douglas"), *bCh) |
          for (admin, tally <- bCh) {
// result should have a list of thee elements but only gets ["caps"]
            trace!(["caps",*admin,*tally])|
// clearly the admin and tally capabilities are working fine below but I am unable to save them for later use.
            trace!({"Issue returned": *admin}) |
            admin!("giveRightToVote", "Owans", *v1Ch) |
            admin!("giveRightToVote", "jimscarver", *v2Ch) |
            admin!("giveRightToVote", "aviation_hacker", *v3Ch) |
            admin!("giveRightToVote", "momchilov", *v4Ch) |
            for(v1 <- v1Ch; v2 <- v2Ch; v3 <- v3Ch; v4 <- v4Ch) {
              v3!("delegate", "jimscarver", *v2Ch) |
              v2!("delegate", "Owens", *v1Ch) |
              v2!("delegate", "Owans", *v4Ch) |
              for(_ <- v2Ch; _ <- v1Ch; _ <- v4Ch ) {
                trace!("voting.") |
                v1!("vote", "Lincoln", *trace, *v1Ch) |
                v1!("vote", "Douglas", *trace, *v2Ch) |
                v1!("vote", "Abe Lincoln", *trace, *v3Ch) |
                v4!("vote", "Lincoln", *trace, *v4Ch) |
                for(_ <- v1Ch; _ <- v2Ch; _ <- v3Ch; _ <- v4Ch) {
                  trace!("votes done") |
                  tally!(*bCh) |
                  for(@w <- bCh) {
                    trace!({"tally": w})
                  }
                }
              }
            }
          }
        }
        
      }
    }}
  }
```
result
```scala
[
  {
    "ExprPar": [
      "voting.",
      "votes done",
      "creating Issue",
      {
        "tally": {
          "Lincoln": 4
        }
      },
      {
        "unknown proposal": "Abe Lincoln"
      },
      {},
      [
        "caps"
      ]
    ]
  }
]
```

### What version of RNode are you using?
testnet
### What is your environment?
https://github.com/rchain-community/liquid-democracy/tree/add-issue
this is holding up progress because when sending a map of the capabilities to the inbox the map turns out to be empty.

**Comment by jimscarver** [comment]
Is there any way to enforce the object capability model before this bug get fixed?

**Comment by jimscarver** [comment]
here is a little simpler example
```scala
match ["inbox", `rho:id:ohyqkr5jmritq8chnwijpufbx3tan6d1hffiksg9qiz9rmuy97a51t`] {
  [lockerTag, InboxURI] => {
    
    new deployId(`rho:rchain:deployId`), deployerId(`rho:rchain:deployerId`),
    lookup(`rho:registry:lookup`), insertArbitrary(`rho:registry:insertArbitrary`),
    inboxCh, capabilities, ret
    in {
      lookup!(InboxURI, *inboxCh) |
      for (Inbox <- inboxCh) {
        Inbox!(*capabilities) |
        for (receive, send, peek <- capabilities) {
          insertArbitrary!(*send, *ret)|
          for (@uri <- ret) {
            @[*deployerId, lockerTag]!({"inbox": *send, "receive": *receive, "peek": *peek, "URI": uri}) |
            deployId!(["#define", "$" ++ lockerTag, uri])
          }
        }
      }|
// read what we wrote? everything but the URI is missing.
      for (x <- @[*deployerId,lockerTag]) {
        deployId!(*x)
      }
    }
  }
}
```
result
```scala
deployId: a51186d6c73756effe24ca2768b7cfd64a1084c3b4c88ae1248ddec8d35035081f8ab0b6f244b31b41419ac8806d1c2aa30aafd872117aa27f32b8755850a9861b 
[
  {
    "ExprPar": [
      [
        "#define",
        "$inbox",
        "rho:id:hnq9eno5r35t6iiyp8houg5fa7wfrhox44mn7aty3wjry6adgcaoyd"
      ],
      {
        "URI": "rho:id:hnq9eno5r35t6iiyp8houg5fa7wfrhox44mn7aty3wjry6adgcaoyd"
      }
    ]
  }
]
```
the capabilities are all lost when written. This worked perfectly until recently.

**Comment by tgrospic** [comment]
@jimscarver It seems that `admin` and `tally` are unforgeable names in a _bundle_ which is not converted to JSON and not returned in the list.

I'll change the title of the issue to fix WebAPI to convert unforgeable names in bundles also.

The question is about the format. If it's a string like `bundle+{7f139...933da}`, it will be much more difficult to handle it on the client side. Maybe a list like `["bundle+", "7f139...933da"]` so that unforgeable name is still alone hex string.

**Comment by jimscarver** [comment]
I see. The capabilities are really there but are invisible. I change the example above to return the size and keys of the map
```
        deployId!(*x.size(),*x.keys().toList(),*x)
```
result
```
"ExprPar": [
     4,
      [
        "URI",
        "inbox",
        "peek",
        "receive"
      ],
      {
        "URI": "rho:id:p198ajijeez4oq9xbwjkaqnta8g5h5rpbnanioztwhyzfbbk96gef8"
      }
```
We get an error in rholang code if we try to output the Set of keys without converting to a list.

**Comment by jimscarver** [comment]
since this always worked before the newer release shouldn't fixing it be labeled a bug rather than an enhancement?

**Comment by tgrospic** [comment]
@stanislavlyalin To resolve this issue we need to recognize if Rholang process is wrapped in a _bundle_ and in conversion to JSON just return what is inside. I don't think it's necessary to support special JSON notiation for bundles.

So output for `bundle0{*x}` will be the same as just `*x`.

What we need to change is Rholang protobuf type to `RhoExpr` converter.
https://github.com/rchain/rchain/blob/f8d7f16d73e8093b4573ed1d8d6f20529e4f1fa5/node/src/main/scala/coop/rchain/node/api/WebApi.scala#L256-L262

Additionally we need this function to extract bundles from `Par` type. In the same way how `par.exprs` and `par.unforgeables` are already handled.
_NOTE: concatenation of `Seq` is OK regarding performance because all collections on Par type are of type `Vector`.
https://docs.scala-lang.org/overviews/collections-2.13/performance-characteristics.html_
```scala
private def exprFromBundleProto(b: Bundle): Option[RhoExpr] = exprFromParProto(b.body)
```

`Par` type represents any Rholang term.
For example (little simplified):
Rholang term `x | 42 | x!(42)`
is Scala object `Par(exprs = Seq(Expr(42)), unforgeables = Seq(GUnforgeable(...)), sends = Seq(Send(...)))`.

With this addition applied WebAPI should return `42` instead of empty result for this deploy.
```scala
new return(`rho:rchain:deployId`) in {
  return!(bundle0{42})
}
```

**Comment by jimscarver** [comment]
Port check tracked in the Rust rewrite: rchain-community/rchain-rust#42.
