### ISSUE TITLE
Improve concurrent block validation (optimize or remove channels map)

### ISSUE THREAD

**Issue by nzpr** [rchain/rchain#3346]
## Overview
Parallel block validation should be improved. Currently disconnection between channels in event log an real channels requires maintaining a map, and its quite costly 
<img width="1783" alt="Screenshot 2021-02-10 at 22 49 11" src="https://user-images.githubusercontent.com/1746367/110436120-e2167500-80c4-11eb-9fdf-341ee9a8c122.png">

### Impact
https://github.com/rchain/rchain/blob/cf7943ef955474b0f5b53c3530ee8a5625eadffc/rspace/src/main/scala/coop/rchain/rspace/history/HistoryRepositoryImpl.scala#L238-L240 

Also there might be another obstacles preventing efficient parallel validation, the entry point for investigations is 
https://github.com/rchain/rchain/blob/3afeda6ff0ac8a2711ce7448b2d8dcc2e186d60a/node/src/main/scala/coop/rchain/node/instances/BlockProcessorInstance.scala#L15-L21

### Dependencies
_

### Design
_

### Steps to implement the solution
At the moment main thesis why concurrent validation is slower than expected is because of maintaining channels map. Optimising this code is a way to go, as it won't be removed completely for some time. Other bottlenecks should be investigated as well.

### Steps for integration testing
_

### Resource estimation
_

**Comment by nzpr** [comment]
After this issue is resolved, tests for block processor should be implemented as per https://github.com/rchain/rchain/pull/3355#discussion_r610344614

**Comment by dckc** [comment]
In [227 Apr 23 Community Debrief](https://blog.rchain.coop/2021/04/23/debrief-227/), @9rb reports that a hard fork is needed in addition to block merge to get RChain to perform / scale as designed. I asked for a pointer to the relevant issue and @nzpr suggested this one.

Since this is preventing RChain from scaling as designed, I suggest changing the label from an enhancement to **bug** and changing the title to "channels map interferes with parallel block validation". (A **performance** label would be a nice touch.)

Also, the [Block merge milestone](https://github.com/rchain/rchain/milestone/4) is **Past due by 29 days**; please update it to represent your best guess.

And if addressing this issue requires a hard fork, perhaps it belongs on a later milestone?

**Comment by tgrospic** [comment]
Channels map removed in linked PR.
