### ISSUE TITLE
Arithmetic overflow in rholang

### ISSUE THREAD

**Issue by wangjia184** [rchain/rchain#3369]
The rholang interpreter does not raise error when arithmetic overflow occurs.
e.g. `9223372036854775807`L + `9223372036854775807`L = `-2`
This is because it inherits from Scala(JVM)'s nature 
https://github.com/rchain/rchain/blob/dev/rholang/src/main/scala/coop/rchain/rholang/interpreter/Reduce.scala#L535

While in Rust, arithmetic overflow panics the process by default because Rust is more strict.

How does rholang spec define this behaviour?

I am implementing the rholang runtime in Rust, and keeps the same behaviour as Scala edition for arithmetic overflow.
https://github.com/wangjia184/rholang-rust/blob/main/rho_runtime/src/interpreter/reduce/expression/plus.rs
Not sure if that is expected, or I am making the same mistake?

**Comment by zsluedem** [comment]
https://github.com/rchain/rchain/issues/2956 related

**Comment by zsluedem** [comment]
also answer to https://github.com/rchain/rchain/issues/2956#issuecomment-813748515
I don't have a concrete plan to resolve this kind of problem. I think we would just leave this problem as it is(overflow) like any other language. 

Besides, rholang provide a [NonNegativeNumber.rho](https://github.com/rchain/rchain/blob/13be1a71b8f59016179af832a0a00d7a0a96b282/casper/src/main/resources/NonNegativeNumber.rho) library for user to avoid that. The library is not perfect right now because of [Peek](https://github.com/rchain/rchain/issues/3200) but that should be the solution for user perspective. 

This is [how eth do](https://github.com/ConsenSysMesh/openzeppelin-solidity/blob/master/contracts/math/SafeMath.sol) I think.
