### ISSUE TITLE
Change rejected deploys in block to be a flag

### ISSUE THREAD

**Issue by tgrospic** [rchain/rchain#3372]
## Overview

With PR #3304 rejected deploys list are added to block message. When validator creates a merged block it can specify which deploys are rejected (ignored) in the current merging scope which contains all blocks from tips to Last Finalized Block (LFB). Later, with new blocks, in the new merging scope rejected deploys can be changed and previously rejected now can again be included. So this means as part of process of merging some deploys can be rejected in one block and included again in later blocks (or vice versa).

To more easily track these transformations we need to extend the format of rejected deploys inside of block to have a flag for each deploy if it's rejected or not.

**Comment by zsluedem** [comment]
Currently the node doesn't get the ability to judge whether the deploys are `unrejected`. This might need another issue for that.

**Comment by tgrospic** [comment]
> Currently the node doesn't get the ability to judge whether the deploys are `unrejected`. This might need another issue for that.

I agree, this should be another PR (it can be linked to this issue though).

@nzpr Can you take over this part? We need to update rejected deploys from current merge but also all previously mentioned as rejected.

Because we have a flag now for rejections, I suggested to rename this field inside block as *conflicting* or similar.
https://github.com/rchain/rchain/pull/3373/files#r609653508

**Comment by nzpr** [comment]
I have a feeling that this unrejection contradicts with how merging is done now - because if we choose to take one of parents post state as a base state for merge - we have to agree with conflict resolution done by that parent. 

Let me outline whats on my mind.

I'm thinking about the following (illustration here just to point to M1 M2 M3):

              *     -> M3
          /      \
         *        *     -> M1 and M2
       /   \    /   \
      *       *      *
       \   /    \   /
         *        *
           \      /
              * 

1) Each `LFB` is ultimate decision on conflict detection inside previous merging scope. All merging in between creates a path towards next `LFB+1` block.
2) Each new `merge block` inherit rejected deploys from one of its parents - the parent which will be used as a base state for merge. E.g. when new `merge` block M3 is created, it reads rejected sets `RjS1` and `RjS2` from `merged` blocks (M1 and M2). **But only one of rejected sets** will be applied to merging scope, so conflict resolution from parent chosen as a base state is in. After adjusting merging scope CD (conflict detection) is executed, potentially adding something else to Set of rejected deploys.
3) When LFB advances, this is finalisation of rejections for deploys that lead from previous LFB to the next one.
4) This set of rejected deploys would infinitely grow if not purged. But - when LFB advances, this is the moment of purge. When creating new block we deduct rejected in latest LFB from set of rejected in parent that is the base state for merge.

**Comment by tgrospic** [comment]
No applicable anymore.
