### ISSUE TITLE
Proposal : A new key mapping design

### ISSUE THREAD

**Issue by wangjia184** [rchain/rchain#3399]
## Background

In Rho-Calculus, Process(name) can be everything. In most cases it is just a ground type(string/int/etc) or unforgeable name. But in unusual  case it can be a composite process, e.g. (`@{ Nil | if(true) {} }`) . When producing or consuming towards a name, the name is the key to locate in tuplespace.  Hence, current RNode gets a unique key by following procedure.

```
ADT ====encoding-with-protobuf====> BUFFER  ====hashing-with-blake2====>  256bit hash
```

This procedure can be simply seen as mapping an ADT into an unique key of one-dimensional space.

## Goals

- It should be faster in most cases than current approach
- It should be able to be implemented in both languages(Scala/Rust)
- The serialization result must be compatible between different platform(JVM/Rust)
- The Rust edition must not allocate on heap during this procedure

## Proposal

Given that LMDB allows its key length up to 512bytes by default,  I suppose the key is in the format below.

```
+-------------+--------------------------------------+
|   Flags     | Various Payload                      |
|   (1 byte)  | (Length must not exceed 511 bytes)   |
+-------------+--------------------------------------+
```

* **Various Payload** differs depending on flags
* **Flags** is an bitwise enum. Its higher-4-bits indicates the data type; Its middle-2-bits indicates the encoding method; Its lower-2-bits indicates the hash method.

```
// for higher-4 bits
enum DataType {
  Composited = 1
  UnforgeableName = 2,
  64bit Integer = 3,
  Boolean = 4,
  String = 5,
  ByteArray = 6,
}

// for middle-2 bits
enum EncodingMethod {
  Raw = 0, //  No encoding
  CapnProto = 1,  // Cap'n Proto
  Protobuf = 2, // 
}

// for lower-2 bits
enum HashingMethod {
  Plaint = 0,  // No hashing
  Blake3 = 1, // Blake3 512bit? (TBD)
  Blake2b256 = 2, // dont think need it.
}
```

Now let's see some examples.

### Ground Number 1,099,511,892,096

Flag = 0x30(00110000)
Payload = 0x8008040000010000 (little endian representation of 64bit signed integer)
Total size = 9 bytes

### UnforgeableName 

Flag = 0x20(00100000)
Payload = the bytes array of unforgeable name, 256bit If I am correct.
Total size = 33 bytes

### String Shorter than 63 bytes

Flag = 0x50(01010000)
Payload = utf8 byte array of the string without BOM
Total size = string's Utf-8 length + 1

### Byte array shorter than 63 bytes

Flag = 0x60(01100000)
Payload = the byte array itself
Total size = byte array length + 1

### Composited type whose length shorter than 63 bytes

Flag = 0x14(00010100)
Payload = The binary result encoded by Cap'n Proto
Total size = the binary result length + 1

### String Longer than 63 bytes

Flag = 0x51(01010001)
Payload = Blake3 hash result of utf8 byte array of the string without BOM
Total size = hash length + 1

### Composited type whose encoding is longer than 63 bytes

Flag = 0x15(00010101)
Payload = first the type is encoded by  Cap'n Proto, then a hash is generated bashing on the encoded result
Total size = hash length + 1

# The fastest code is code that doesn't run at all

For most cases( I estimate > 90%), we don't need serialization or hashing; The key length is same as current one, or even shorter.
Only when the name is complicated or string is too long, encoding or hashing is involved. Its performance must be better than current approach.  And this format allows to extend in some degree.

This is just a proposal, many details could change

BTW  Scala do not have Blake3 lib, that is not a problem. We can have a *.so/*.dll exposing JNI interface for Scala to use. It is X times faster . We even can think about use it for unforgeable names as well.

**Comment by zsluedem** [comment]
https://github.com/rchain/rchain/issues/3384 related

**Comment by tgrospic** [comment]
@wangjia184 I really appreciate your suggestion.

First I want to focus on names that makes the keys and the storage.
Names that are created from primitive types are for sure legitimate but when used on-chain does not make to much sense because they can be forged. That's way the need for unforgeable names are essential.
So composite names like `@(<hash>, 42)` will be mostly used where unforgeable name (hash) will be used to create another one. Together with _bundling_ (to protect read/write access) names gives the Rholang very powerful capabilites.

Another important thing is how names as stored or used as keys to store the data or continuation.
To be able to calculate the hash of the whole state (tuple space) names are encoded in a radix tree with leafs holding the values. More specific structure that offers calculating a proof is Merkle-Patricia Trie form which we can obtain unique root hash for the whole state.
If keys are different length, it makes harder to encode because it needs additional markers and also for long keys it needs more traversals when read and also more space when tree is sparse.
I made performance testing of our current implementation of History #3382 because this is something that we are looking to of load from Scala to increase performance.

Regarding serialization I noticed that the most of time is spent on encoding/decoding body of continuation because it's usually the largest part of the code.

Scala has two libraries for Blake3 already (JNI to C and pure Scala). I'm not sure if they are ready to replace Blake2. 
https://github.com/sken77/BLAKE3jni
https://github.com/catap/scala-blake3

And I agree, the best code is not written at all. :smile:

**Comment by wangjia184** [comment]
Thanks @tgrospic for explanation, now I start to understand [these strange codes](https://github.com/rchain/rchain/blob/dev/rholang/src/main/scala/coop/rchain/rholang/interpreter/Reduce.scala#L170-L173) . 

It seems its purpose is to avoid the radix tree to fan-out too fast.  Still don't get a clear mind about all the stuff like Merkle-Patricia Trie, how they are organized across blocks.   The encoding/hashing happens for every send/receive, that is one of the factors making rholang slower than other languages and I want to get rid of it.  Anyhow, I can't provide a reasonable solution without modeling the entire system in mind.  Close this task first.

**Comment by tgrospic** [comment]
@wangjia184 to be able to record execution on the blockchain every produce/consume is marked with generated hash with the seed from previous scope. In that way it creates like a trace of execution.
The code you mentioned is basically the place where Rholang _par_ operation has to be split and the pseudo random generator has to split the seed also `seedParent  -->  seedParentLeft | seedParentRight`. Left and right can be then executed in parallel but generated unforgeable names will always have distinct hashes.

I found improved radix tree with dynamic nodes to save space in case of sparse tree.
https://db.in.tum.de/~leis/papers/ART.pdf
Here is also C implementation.
https://github.com/armon/libart
To get Merkle tree, children nodes needs to be hashed so it's possible to get the root hash. But from RSpace perspective this is like a Map where channel hash is the key and value is data or continuation.

**Comment by wangjia184** [comment]
@tgrospic Very essential question here

> To get Merkle tree, children nodes needs to be hashed so it's possible to get the root hash.

What is the transaction in rholang which makes up the leaves in Merkle tree?
A transaction is a send(receive)?  or a matched  COMM events? Or a deployed par?

**Comment by wangjia184** [comment]
> Here is also C implementation. https://github.com/armon/libart

We can use it as a black-box by static-linking it via FFI in rust :)

**Comment by zsluedem** [comment]
> @tgrospic Very essential question here
> 
> > To get Merkle tree, children nodes needs to be hashed so it's possible to get the root hash.
> 
> What is the transaction in rholang which makes up the leaves in Merkle tree?
> A transaction is a send(receive)? or a matched COMM events? Or a deployed par?

RChain only got one state merkle tree which is not like ETH (World State Trie,Transaction Trie,Receipt Trie,Account Storage Trie).  RChain state trie represent what's left in the tuplespace. You can take that as Tuplespace Trie
