### ISSUE TITLE
Startup and migration error with v0.11.0-rc1

### ISSUE THREAD

**Issue by tgrospic** [rchain/rchain#3471]
## Overview

Testing `v0.11.0-rc1` version revealed errors in startup on test net in the process of getting the Last Finalized State and on main net when node started migration of LFB to DAG storage.

Test net logs:
[test-net-fresh-start-error.log](https://github.com/rchain/rchain/files/6794888/test-net-fresh-start-error.log)

Main net logs:
[main-net-migration-error.log](https://github.com/rchain/rchain/files/6794889/main-net-migration-error.log)

**Comment by nzpr** [comment]
I believe that error with main net is because of this change 
https://github.com/rchain/rchain/blob/a580f8f7210172d1e99c43f6871a44bb20a7576d/block-storage/src/main/scala/coop/rchain/blockstorage/finality/LastFinalizedKeyValueStorage.scala#L61-L66

it gathers edge parents that are not in metadata store. S it should be 
```scala
finalizedBlockSet <- DagOps
                            .bfTraverseF(List(lfb)) { bh =>
                              blocksInfoMap
                                .get(bh)
                                // with trimmed state edge parents might not be in the blockmetadataDB, so filter them out
                                .map(_.parents.toList.filterA(blockMetadataDb.contains(_)))
                                .getOrElse(List.empty[BlockHash].pure)
                            }
                            .toList
```

Error on testnet is because approved block is inserted right away here https://github.com/rchain/rchain/pull/3459/files#r661767723, and for some reason the next block added is #151983, while approved block is #152033. Not sure yet why.

**Comment by tgrospic** [comment]
> Error on testnet is because approved block is inserted right away here https://github.com/rchain/rchain/pull/3459/files#r661767723, and for some reason the next block added is #151983, while approved block is #152033. Not sure yet why.

Approved block is not the first block that is part of the LFS state because some amount of older blocks are required for deploy lifetime check.

**Comment by nzpr** [comment]
Yes, we add blocks starting from the oldest to newest, I think because it is forced by DagStore.
But we need to insert LFB first because each subsequent DagStore.insert returns DagRepresentation, which requires DagStore to already have some LFB.
