### ISSUE TITLE
Add no-box option to routing protobuf definition

### ISSUE THREAD

**Issue by tgrospic** [rchain/rchain#3548]
## Overview

Protobuf definition for routing protocol (routing.proto) contains generated Scala code with fields as `Option` types.

When protobuf defined types have fields with complex types, generated Scala classes contains these fields wrapped in `Option` type by default. This is not convenient, doesn't help and just requires on every use to handle partial values.

## Solution

Add `no-box` option in proto definition and update places where generated code is used.
Some places where this should be changed:
https://github.com/rchain/rchain/blob/382576eb9030c7a03fdff0d75a8a2a41e80dc378/models/src/main/protobuf/routing.proto#L24-L27
https://github.com/rchain/rchain/blob/382576eb9030c7a03fdff0d75a8a2a41e80dc378/models/src/main/protobuf/routing.proto#L51-L52

Examples where this is already used:
https://github.com/rchain/rchain/blob/382576eb9030c7a03fdff0d75a8a2a41e80dc378/models/src/main/protobuf/RhoTypes.proto#L58-L59

**Comment by stanislavlyalin** [comment]
@tgrospic, a few questions:
1. should `no_box` option be added only in [routing.proto](https://github.com/rchain/rchain/blob/382576eb9030c7a03fdff0d75a8a2a41e80dc378/models/src/main/protobuf/routing.proto) file?
2. is it possible to add `no_box` option for complex types inside `oneof` section? I found that it leads to errors in generated code.
3. adding `no_box` option to field `ChunkHeader.sender` leads to failure in test ["should stop processing a stream if stream is missing part of header"](https://github.com/rchain/rchain/blob/3b72ba23db5b938e389687168787030f0adaa246/comm/src/test/scala/coop/rchain/comm/transport/StreamHandlerSpec.scala#L64), because the header is now doesn't incomplete. How to better fix the test?
4. is it needed to add `no_box` option to field `TLRequest.protocol`? According to `send` method request of type TLRequest can be incorrect, but it follows from the calling code that the request cannot be `None`:
https://github.com/rchain/rchain/blob/382576eb9030c7a03fdff0d75a8a2a41e80dc378/comm/src/main/scala/coop/rchain/comm/transport/GrpcTransportReceiver.scala#L103-L106

**Comment by tgrospic** [comment]
1. Yes, only in routing.proto file
2. Fields defined with `oneof` are not wrapped in Option type so no action there is necessary
3. This test can be deleted because there is no optional values
4. Yes, we want to remove checking of optional values
