### ISSUE TITLE
Multi-sig contract not working with public keys

### ISSUE THREAD

**Issue by tgrospic** [rchain/rchain#3647]
### What did you expect to see?

When multi-sig contract is created with public keys it should be possible to use these keys to create/confirm transfers.

### What did you see instead?

Multi-sig contract returns an error with `invalid auth`̣ when used by the deployer which has its public key defined for multi-sig. 

### Steps to reproduce the bug

1. Create multi-sig with at least one public key defined and at least minimum quorum size.
2. Create a deploy with the private key defined for multi-sig.
3. Observe an error `invalid auth` instead of transfer result.

More detailed steps now multi-sig can be used are specified as part of the issue for PoS config parameters.
- #3625.

### What version of RNode are you using?

v.0.12.5 (but it should be any version of the node)

### Problem

The issue is that AuthKey contract used in multi-sig contract is used in a wrong way so it's not possible to authenticate the deployer with corresponding public key defined when multi-sig vault is created.
Tests for multi-sig with public keys are not written so this issues is never detected. All multi-sig vaults created with public keys access are locked like the one defined in PoS for slashed funds owned by Coop.
https://github.com/rchain/rchain/blob/888c80408925d8c471928c920644959e43f52752/casper/src/main/resources/PoS.rhox#L105-L117

After solving the problem with AuthKey another problem showed up with multi-sig vault. When checking boolean expression which is executed eagerly exception is thrown for accessing index out of range because code is expecting for second argument of boolean operator not be executed (`unsealers.nth(info.nth(0))`).

https://github.com/rchain/rchain/blob/942c6ef4323edca016bd0c8a304a2e5c022d8563/casper/src/main/resources/MultiSigRevVault.rho#L202-L203

- #3362

### Solution

The fix for the use of AuthKey is done in these two PRs.
- #3639
- #3643

We need this fix immediately to start the RPC main net so PRs with patches should also be created for `v0.12.5` version.
- #3641

The epic to track all changes for RPC is tracked in this issue.
- #3642

To solve the issue with boolean operators Rholang bug should be fixed, but because we want to have RPC version ASAP Greg suggested that the solution should be creation of the special method which will handle the boolean logic that is needed for this purpose.

**Comment by zsluedem** [comment]
I create a [test](https://github.com/rchain/rchain/pull/3648) for transfer from Pos MultiSig. 
I saw `coop.rchain.rholang.interpreter.errors$ReduceError: Error: index out of bound: -1)` . Is that what you see the case and get the conclusion of boolean operator bug?

**Comment by zsluedem** [comment]
Let me simplify the question which you don't need to know any details of the PoS, RevVault.Please **forget** about these application logics and focus on the** language layer**. The application concepts should not get into your head right now to save time. To put it into simple case. The goal is to make a boolean evaluation as short as possible. @dharsh#4553 I think you know some Python so I just show you some examples in Python.

For a `AND` boolean evaluation like 
```python
False and [1,2].index(-1)
```
because the first one is `False`, in the `AND` situation, no matter what the left boolean is , the whole boolean expression is still be `False`.  So in this situation, the rest `[1,2].index(-1)` should not be evaluated although `[1,2].index(-1)` would throw exception.

Likewise in `OR` boolean evaluation
```python
True or [1,2].index(-1)
```
Reason like above.

In the rholang case would be 
```
false and [1,2].nth(-1)
```
