### ISSUE TITLE
squash merge policy / preference?

### ISSUE THREAD

**Issue by dckc** [rchain/rchain#65]
eebbdd8 for #60 attributes a whole bunch of stuff to me that is actually from Kent's stuff that I rebased.

Do you guys want stuff squashed? I asked in #40 but didn't hear anything. If you want stuff squashed, I'll try to do that so that you don't have to do a squash merge. It would be nice to have this documented in a CONTRIBUTING.md.

(escalated from https://github.com/rchain/rchain/pull/60#issuecomment-347358177 )

**Comment by tymm** [comment]
I think we haven't officially decided yet on a policy. I'm in favor of squashing and changing the commit message to only relevant stuff (no `* Fixed typo` type content).
Any other opinions on that?

Something like a `CONTRIBUTING.md` is a good idea. I think @echatav is working on that?

**Comment by echatav** [comment]
Wasn't particularly but I could add that; what I had suggested was per module owners but that was rejected. What were you thinking should be in `CONTRIBUTING.md` and should there be 1 per subproject or just 1 for all of the `rchain` project?

**Comment by tymm** [comment]
I was thinking about one for the `rchain` project where we describe how to submit pull requests and so on.

**Comment by echatav** [comment]
I will add one to my in progress branch and we can fix it up to match what you're thinking.

**Comment by dckc** [comment]
> What were you thinking should be in `CONTRIBUTING.md` ?

See [Setting guidelines for repository contributors](https://help.github.com/articles/setting-guidelines-for-repository-contributors/).

**Comment by dckc** [comment]
oh... and a link to the scala style guide in JIRA. I can't find it just now.

**Comment by echatav** [comment]
For now I put links to relevant JIRA documentation in the `CONTRIBUTING.md`. This has been merged into `master` and there's an open PR for `dev`.

**Comment by MParlikar** [comment]
Everyone, can we leave squashed merges on for now, and agree that we won't re-base off of others un-approved PR's?  I'd like to close this issue.  Also, in Contributing.MD, do we have a link to create Jira issues?  https://rchain.atlassian.net/secure/CreateIssue!default.jspa

**Comment by elwaheed** [comment]
Yas

**Comment by dckc** [comment]
"won't re-base off of others un-approved PR's" is effectively a policy against helping someone finish a feature... Or in general, against more than one person contributing to a PR. That seems counterproductive, to me.

**Comment by MParlikar** [comment]
I don't see how it is a policy against helping someone finish a feature.  It is a policy against having more than 1 person working on a single PR. I don't see the benefit of making our merges to dev and master significantly more noisy to support this use case (which at the moment,  is more the exception than the rule).

**Comment by dckc** [comment]
Kent started a travis CI branch. I picked up where he left off. A "won't re-base off of others un-approved PR's" policy says I should not have done that. That is: that I should not have helped him finish that feature. Or that I should have finished the feature without re-using his work.

**Comment by MParlikar** [comment]
You can work on the same branch. What you shouldn't do is re-base off of a PR.  The PR should be approved and merged first.  Then do a fresh get and make your changes.

**Comment by dckc** [comment]
Maybe a picture helps.

![rchain-travis-work](https://user-images.githubusercontent.com/150986/34238515-a87d9652-e5c7-11e7-8edc-0df56bb73703.png)

I started working on this stuff around Nov 20. At that point, Kent's https://github.com/rchain/rchain/pull/52 was pending, with 21be575 as its head, branched from dev as of Nov 8. It wasn't finished. Kent asked me to finish it.

I got something working and opened PR 54, but it was a bit of a mess, because between Nov 8 and Nov 10, there was a big directory re-organization (you can't see the mess now because I used the same branch name, `travis-each-dir` for PR54 and PR64 and force-push erased what PR54 used to look like). So I re-based my `travis-each-dir` branch against Nov 10 dev cd3964f and submitted PR 60. Kent's work from PR52 got rebased as a by-product.

It wasn't possible for me to contribute to PR52; I didn't (and don't) have access to push to `dev-kent-travis-experimental`. It didn't work, so I wouldn't have approved it, even if I had access. Nor did I have access to merge it to master. What would be the thing to do starting Nov 20 according to the policy you're aiming for?

As a contributor, I'd rather you just told me you want commits squashed before PRs are submitted (e.g. in answer to the question I asked Nov 3 in #40). I wouldn't squash Kent's work and my work together in one commit, but I could squash his commits in one commit and then my commits in another; asking that you merge a PR with two commits doesn't seem onerous. As you say, this would most likely be the exception. I'll deal with whatever policies the project puts in place. But that's my preference.

**Comment by dckc** [comment]
I'm reviewing recent work to see what the project norms are. Other merges don't seem to get squashed; even minor formatting tweaks like a91afe4 and 374cdcd in #98.

**Comment by nashef** [comment]
Ok, executive decision time.

First, squashed commits bother me for two reasons. They eliminate part of the history and they encourage people to write low quality commit messages when working locally. Both of those are suboptimal behaviors. ***We're not going to squash commits for now.*** If you want to argue for squashing, then come up with a good reason why it's better and how we should use it. I'm open-minded, but I haven't heard a solid argument beyond aesthetics.

Second, rebasing isn't inherently wrong, but if it causes changes to mis-attributed, then it's no good _in that case_. I have to be honest that I've never actually needed to use rebase while developing, but on the other hand I have known people that use it successfully. I suppose YMMV.

Regardless, here's the rule that you should follow: **When you're picking up someone else's pull request, then whatever you do must preserve the commit history.** If you can accomplish that by rebasing off someone else's PR, then great. I think that's fine. If you need to merge the PR and then create a new PR, then I think that's also fine. Merging a broken PR and then fixing it "later" is the least preferable, but there are situations where this also works. E.g., if the "fix" is already implemented and will be merged almost immediately.

There really are no simple solutions with git, only simple problems with complex solutions. So, just try to keep in mind that the goal of revision control is to keep track of the revisions. That doesn't happen if we fail to preserve history in detail.

Dan, since you opened the bug, please add comments to roughly the above effect to `CONTRIBUTING.md` and send me a pull request with the change. Then close this bug.

Regards,

  --nash

**Comment by dckc** [comment]
will do, @nashef ; I'm mostly in holiday mode now, but I expect to get to it in due course.

**Comment by nashef** [comment]
Can we make this happen now?

**Comment by MParlikar** [comment]
@pyrocto please disable squash merges.

**Comment by nashef** [comment]
Is it something that can be disabled? I get a choice every time I do a PR.

**Comment by pyrocto** [comment]
Done.

**Comment by nashef** [comment]
LGTM
